# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Michael Galperin
tagline:          'A Jekyll theme'
description:      'Hi! I'm a Ph.D. Student in Economics at UChicago and an affiliate of <a href="https://twitter.com/UChiEnergy" target="_blank">EPIC</a> and the <a href="https://twitter.com/impact_lab?lang=en" target="_blank">Climate Impact Lab.</a>'

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

