# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Michael Galperin
tagline:          'A Jekyll theme'
description:      'Ph.D. Student in Economics at UChicago. Affiliate, <a href="https://twitter.com/UChiEnergy" target="_blank">EPIC</a> and the <a href="https://twitter.com/impact_lab?lang=en" target="_blank">Climate Impact Lab.</a>'
url:              http://michaelgalperin.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
